"""simple model design

Revision ID: 3d5105817540
Revises: 
Create Date: 2020-02-14 19:36:30.957280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5105817540'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'))

    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=True),
    sa.Column('company_symbol', sa.String(length=128), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('trans_type', sa.String(length=128), nullable=False),
    sa.Column('transacted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'))
    
    op.create_index(op.f('ix_transactions_company_name'), 'transactions', ['company_name'], unique=False)
    op.create_index(op.f('ix_transactions_company_symbol'), 'transactions', ['company_symbol'], unique=False)
    op.create_index(op.f('ix_transactions_trans_type'), 'transactions', ['trans_type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_trans_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_symbol'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_name'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
