"""add tables & relationships for /buy

Revision ID: 465902c5347e
Revises: 82bc78da44ca
Create Date: 2020-02-12 19:16:48.573662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465902c5347e'
down_revision = '82bc78da44ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('company_symbol', sa.String(length=128), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_company_name'), 'stocks', ['company_name'], unique=False)
    op.create_index(op.f('ix_stocks_company_symbol'), 'stocks', ['company_symbol'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('transacted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_stocks_company_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_company_name'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
