"""migrate users table

Revision ID: 82bc78da44ca
Revises: 
Create Date: 2020-02-05 04:49:50.809943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bc78da44ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'users', ['username'], unique=1)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
