"""minor adjustments in models

Revision ID: ac21d9a9a35c
Revises: 465902c5347e
Create Date: 2020-02-12 19:24:38.024674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac21d9a9a35c'
down_revision = '465902c5347e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.alter_column('stock_id',
                existing_type=sa.INTEGER(),
                nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
